import { prisma } from '../lib/prisma.js';
import {
  CreateTransactionInput,
  UpdateTransactionInput,
  TransactionQuery,
} from '../schemas/transaction.schema.js';
import { NotFoundError } from '../lib/errors.js';
import { updateAccountBalance } from './accounts.service.js';
import { checkBudgetAndNotify } from './notifications.service.js';
import { upsertTags } from './tags.service.js';

export async function getTransactions(userId: string, query: TransactionQuery) {
  const {
    startDate,
    endDate,
    accountId,
    categoryId,
    categoryIds,
    type,
    limit = 50,
    offset = 0,
    tag,
    minAmount,
    maxAmount,
  } = query;

  const where: Record<string, unknown> = { userId };

  if (startDate || endDate) {
    where.date = {};
    if (startDate) (where.date as Record<string, Date>).gte = new Date(startDate);
    if (endDate) (where.date as Record<string, Date>).lte = new Date(endDate);
  }

  if (accountId) where.accountId = accountId;

  if (categoryIds?.length) {
    where.categoryId = { in: categoryIds };
  } else if (categoryId) {
    where.categoryId = categoryId;
  }

  if (type) where.type = type;
  if (tag) where.tags = { some: { tag: { name: tag.toLowerCase(), userId } } };

  if (minAmount !== undefined || maxAmount !== undefined) {
    const amountFilter: Record<string, number> = {};
    if (minAmount !== undefined) amountFilter.gte = minAmount;
    if (maxAmount !== undefined) amountFilter.lte = maxAmount;
    where.amount = amountFilter;
  }

  const [transactions, total] = await Promise.all([
    prisma.transaction.findMany({
      where,
      include: {
        account: { select: { id: true, name: true, color: true } },
        category: { select: { id: true, name: true, icon: true, color: true } },
        fixedExpense: { select: { id: true, name: true } },
        tags: { include: { tag: { select: { id: true, name: true } } } },
        _count: { select: { receiptItems: true } },
      },
      orderBy: { date: 'desc' },
      take: limit,
      skip: offset,
    }),
    prisma.transaction.count({ where }),
  ]);

  return { transactions, total, limit, offset };
}

export async function getTransactionById(id: string, userId: string) {
  const transaction = await prisma.transaction.findFirst({
    where: { id, userId },
    include: {
      account: { select: { id: true, name: true, color: true } },
      category: { select: { id: true, name: true, icon: true, color: true } },
      receiptItems: true,
      tags: { include: { tag: { select: { id: true, name: true } } } },
    },
  });

  if (!transaction) {
    throw new NotFoundError('Transacción no encontrada');
  }

  return transaction;
}

export async function createTransaction(data: CreateTransactionInput, userId: string) {
  const tagIds = data.tagNames?.length ? await upsertTags(userId, data.tagNames) : [];

  const transaction = await prisma.transaction.create({
    data: {
      amount: data.amount,
      type: data.type,
      description: data.description,
      date: data.date ? new Date(data.date) : new Date(),
      accountId: data.accountId,
      categoryId: data.categoryId,
      fixedExpenseId: data.fixedExpenseId,
      isAutoGenerated: data.isAutoGenerated ?? false,
      imageHash: data.imageHash,
      userId,
      receiptItems: data.receiptItems
        ? {
            create: data.receiptItems.map((item) => ({
              name: item.name,
              quantity: item.quantity,
              unitPrice: item.unitPrice,
              totalPrice: item.totalPrice,
            })),
          }
        : undefined,
      tags: tagIds.length ? { create: tagIds.map((tagId) => ({ tagId })) } : undefined,
    },
    include: {
      account: { select: { id: true, name: true, color: true } },
      category: { select: { id: true, name: true, icon: true, color: true } },
      receiptItems: true,
      tags: { include: { tag: { select: { id: true, name: true } } } },
    },
  });

  await updateAccountBalance(data.accountId, data.amount, data.type);

  if (data.type === 'expense') {
    checkBudgetAndNotify(userId, data.categoryId).catch(() => {});
  }

  return transaction;
}

export async function updateTransaction(id: string, data: UpdateTransactionInput, userId: string) {
  const existing = await getTransactionById(id, userId);

  await updateAccountBalance(
    existing.accountId,
    Number(existing.amount),
    existing.type === 'income' ? 'expense' : 'income'
  );

  const updateData: Record<string, unknown> = {};
  if (data.amount !== undefined) updateData.amount = data.amount;
  if (data.type !== undefined) updateData.type = data.type;
  if (data.description !== undefined) updateData.description = data.description;
  if (data.accountId !== undefined) updateData.accountId = data.accountId;
  if (data.categoryId !== undefined) updateData.categoryId = data.categoryId;
  if (data.fixedExpenseId !== undefined) updateData.fixedExpenseId = data.fixedExpenseId;
  if (data.imageHash !== undefined) updateData.imageHash = data.imageHash;
  if (data.date !== undefined) updateData.date = new Date(data.date);

  if (data.tagNames !== undefined) {
    const tagIds = data.tagNames.length ? await upsertTags(userId, data.tagNames) : [];
    updateData.tags = {
      deleteMany: {},
      create: tagIds.map((tagId) => ({ tagId })),
    };
  }

  const updated = await prisma.transaction.update({
    where: { id },
    data: updateData,
    include: {
      account: { select: { id: true, name: true, color: true } },
      category: { select: { id: true, name: true, icon: true, color: true } },
      tags: { include: { tag: { select: { id: true, name: true } } } },
    },
  });

  await updateAccountBalance(
    updated.accountId,
    Number(updated.amount),
    updated.type as 'expense' | 'income'
  );

  return updated;
}

export async function deleteTransaction(id: string, userId: string) {
  const transaction = await getTransactionById(id, userId);

  // Revert balance change
  await updateAccountBalance(
    transaction.accountId,
    Number(transaction.amount),
    transaction.type === 'income' ? 'expense' : 'income'
  );

  return prisma.transaction.delete({
    where: { id },
  });
}

export async function getTransactionSummary(
  userId: string,
  query: Pick<TransactionQuery, 'startDate' | 'endDate' | 'accountId' | 'type'>
) {
  const { startDate, endDate, accountId, type } = query;

  const where: Record<string, unknown> = { userId };

  if (startDate || endDate) {
    where.date = {};
    if (startDate) (where.date as Record<string, Date>).gte = new Date(startDate);
    if (endDate) (where.date as Record<string, Date>).lte = new Date(endDate);
  }

  if (accountId) where.accountId = accountId;
  if (type) where.type = type;

  const rows = await prisma.transaction.groupBy({
    by: ['categoryId', 'type'],
    where,
    _sum: { amount: true },
    _count: { _all: true },
  });

  const categoryMap = new Map<
    string,
    { expenseTotal: number; incomeTotal: number; count: number }
  >();

  for (const row of rows) {
    if (!row.categoryId) continue;
    const entry = categoryMap.get(row.categoryId) ?? { expenseTotal: 0, incomeTotal: 0, count: 0 };
    entry.count += row._count._all;
    if (row.type === 'expense') entry.expenseTotal += Number(row._sum.amount ?? 0);
    else entry.incomeTotal += Number(row._sum.amount ?? 0);
    categoryMap.set(row.categoryId, entry);
  }

  const categoryIds = Array.from(categoryMap.keys());
  if (categoryIds.length === 0) return [];

  const cats = await prisma.category.findMany({
    where: { id: { in: categoryIds } },
    select: { id: true, name: true, icon: true, color: true },
  });

  return cats
    .map((cat) => {
      const data = categoryMap.get(cat.id) ?? { expenseTotal: 0, incomeTotal: 0, count: 0 };
      return {
        category: cat,
        expenseTotal: data.expenseTotal,
        incomeTotal: data.incomeTotal,
        count: data.count,
        netTotal: data.incomeTotal - data.expenseTotal,
      };
    })
    .sort((a, b) => b.expenseTotal - a.expenseTotal);
}

export async function getReceiptItems(transactionId: string, userId: string) {
  // Verify transaction belongs to user
  await getTransactionById(transactionId, userId);

  return prisma.receiptItem.findMany({
    where: { transactionId },
    orderBy: { createdAt: 'asc' },
  });
}
