import type { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma.js';
import {
  CreateTransactionInput,
  UpdateTransactionInput,
  TransactionQuery,
} from '../schemas/transaction.schema.js';
import { buildTransactionWhereInput } from '../lib/utils/transaction.utils.js';
import {
  assertCreditCardLimit,
  CreditCardBalanceInfo,
} from '../lib/utils/credit-card-limit.utils.js';
import { NotFoundError } from '../lib/errors.js';
import { updateAccountBalance } from './accounts.service.js';
import * as transactionRepo from '../repositories/transaction.repository.js';
import * as categoryRepo from '../repositories/category.repository.js';

/**
 * Lee la cuenta con FOR UPDATE dentro de la tx para que la validación de límite
 * de tarjeta y el decremento posterior queden serializados por el lock de fila
 * (un SELECT plano no bloquea: dos requests concurrentes podrían leer el mismo
 * saldo, pasar ambas la validación y dejarlo por encima del límite).
 */
async function lockAccountForBalanceUpdate(
  tx: Prisma.TransactionClient,
  accountId: string,
  userId: string
): Promise<CreditCardBalanceInfo | null> {
  const rows = await tx.$queryRaw<
    Array<{
      type: string;
      creditLimit: Prisma.Decimal | null;
      balance: Prisma.Decimal;
      initialBalance: Prisma.Decimal;
    }>
  >`SELECT type, "creditLimit", balance, "initialBalance" FROM "Account" WHERE id = ${accountId} AND "userId" = ${userId} FOR UPDATE`;

  const account = rows[0];
  if (!account) return null;

  return {
    type: account.type,
    creditLimit: account.creditLimit === null ? null : Number(account.creditLimit),
    balance: Number(account.balance),
    initialBalance: Number(account.initialBalance),
  };
}

export async function getTransactions(userId: string, query: TransactionQuery) {
  const {
    startDate,
    endDate,
    accountId,
    categoryId,
    categoryIds,
    type,
    limit = 50,
    offset = 0,
    minAmount,
    maxAmount,
  } = query;

  const where = buildTransactionWhereInput(userId, {
    startDate,
    endDate,
    accountId,
    categoryId,
    categoryIds,
    type,
    minAmount,
    maxAmount,
  });

  const [transactions, total] = await Promise.all([
    transactionRepo.findMany(where, {
      include: {
        account: { select: { id: true, name: true, color: true } },
        category: { select: { id: true, name: true, icon: true, color: true } },
        fixedExpense: { select: { id: true, name: true } },
        _count: { select: { receiptItems: true } },
      },
      orderBy: { date: 'desc' },
      take: limit,
      skip: offset,
    }),
    transactionRepo.count(where),
  ]);

  return { transactions, total, limit, offset };
}

export async function getTransactionById(id: string, userId: string) {
  const transaction = await transactionRepo.findByIdAndUser(id, userId, {
    account: { select: { id: true, name: true, color: true } },
    category: { select: { id: true, name: true, icon: true, color: true } },
    receiptItems: true,
  });

  if (!transaction) {
    throw new NotFoundError('Transacción no encontrada');
  }

  return transaction;
}

export async function createTransaction(data: CreateTransactionInput, userId: string) {
  return prisma.$transaction(async (tx) => {
    await assertOwnership(
      userId,
      {
        accountId: data.accountId,
        categoryId: data.categoryId,
        fixedExpenseId: data.fixedExpenseId,
      },
      tx
    );

    const account = await lockAccountForBalanceUpdate(tx, data.accountId, userId);
    if (!account) throw new NotFoundError('Cuenta no encontrada');

    assertCreditCardLimit(account, data.amount, data.type);

    const transaction = await tx.transaction.create({
      data: {
        amount: data.amount,
        type: data.type,
        description: data.description,
        date: data.date ? new Date(data.date) : new Date(),
        account: { connect: { id: data.accountId } },
        category: { connect: { id: data.categoryId } },
        fixedExpense: data.fixedExpenseId ? { connect: { id: data.fixedExpenseId } } : undefined,
        isAutoGenerated: data.isAutoGenerated ?? false,
        imageHash: data.imageHash,
        user: { connect: { id: userId } },
        receiptItems: data.receiptItems
          ? {
              create: data.receiptItems.map((item) => ({
                name: item.name,
                quantity: item.quantity,
                unitPrice: item.unitPrice,
                totalPrice: item.totalPrice,
              })),
            }
          : undefined,
      },
      include: {
        account: { select: { id: true, name: true, color: true } },
        category: { select: { id: true, name: true, icon: true, color: true } },
        receiptItems: true,
      },
    });

    await updateAccountBalance(data.accountId, userId, data.amount, data.type, tx);

    return transaction;
  });
}

export async function updateTransaction(id: string, data: UpdateTransactionInput, userId: string) {
  const existing = await getTransactionById(id, userId);

  const updateData: Prisma.TransactionUpdateInput = {};
  if (data.amount !== undefined) updateData.amount = data.amount;
  if (data.type !== undefined) updateData.type = data.type;
  if (data.description !== undefined) updateData.description = data.description;
  if (data.accountId !== undefined) updateData.account = { connect: { id: data.accountId } };
  if (data.categoryId !== undefined) updateData.category = { connect: { id: data.categoryId } };
  if (data.fixedExpenseId !== undefined)
    updateData.fixedExpense = { connect: { id: data.fixedExpenseId } };
  if (data.imageHash !== undefined) updateData.imageHash = data.imageHash;
  if (data.date !== undefined) updateData.date = new Date(data.date);

  const resultingAccountId = data.accountId ?? existing.accountId;
  const resultingType = data.type ?? existing.type;
  const resultingAmount = data.amount ?? Number(existing.amount);

  return prisma.$transaction(async (tx) => {
    await assertOwnership(
      userId,
      {
        accountId: data.accountId,
        categoryId: data.categoryId,
        fixedExpenseId: data.fixedExpenseId,
      },
      tx
    );

    await updateAccountBalance(
      existing.accountId,
      userId,
      Number(existing.amount),
      existing.type === 'income' ? 'expense' : 'income',
      tx
    );

    const resultingAccount = await lockAccountForBalanceUpdate(tx, resultingAccountId, userId);
    if (!resultingAccount) throw new NotFoundError('Cuenta no encontrada');

    assertCreditCardLimit(resultingAccount, resultingAmount, resultingType);

    const updated = await tx.transaction.update({
      where: { id },
      data: updateData,
      include: {
        account: { select: { id: true, name: true, color: true } },
        category: { select: { id: true, name: true, icon: true, color: true } },
      },
    });

    await updateAccountBalance(
      updated.accountId,
      userId,
      Number(updated.amount),
      updated.type as 'expense' | 'income',
      tx
    );

    return updated;
  });
}

export async function deleteTransaction(id: string, userId: string) {
  const transaction = await getTransactionById(id, userId);

  await prisma.$transaction(async (tx) => {
    await tx.transaction.delete({ where: { id } });

    await updateAccountBalance(
      transaction.accountId,
      userId,
      Number(transaction.amount),
      transaction.type === 'income' ? 'expense' : 'income',
      tx
    );
  });
}

export async function getTransactionSummary(
  userId: string,
  query: Pick<TransactionQuery, 'startDate' | 'endDate' | 'accountId' | 'type'>
) {
  const { startDate, endDate, accountId, type } = query;

  const where: Record<string, unknown> = { userId };

  if (startDate || endDate) {
    where.date = {};
    if (startDate) (where.date as Record<string, Date>).gte = new Date(startDate);
    if (endDate) (where.date as Record<string, Date>).lte = new Date(endDate);
  }

  if (accountId) where.accountId = accountId;
  if (type) where.type = type;

  const rows = await transactionRepo.groupByCategory(where as Prisma.TransactionWhereInput);

  const categoryMap = new Map<
    string,
    { expenseTotal: number; incomeTotal: number; count: number }
  >();

  for (const row of rows) {
    if (!row.categoryId) continue;
    const entry = categoryMap.get(row.categoryId) ?? { expenseTotal: 0, incomeTotal: 0, count: 0 };
    entry.count += row._count._all;
    if (row.type === 'expense') entry.expenseTotal += Number(row._sum.amount ?? 0);
    else entry.incomeTotal += Number(row._sum.amount ?? 0);
    categoryMap.set(row.categoryId, entry);
  }

  const categoryIds = Array.from(categoryMap.keys());
  if (categoryIds.length === 0) return [];

  const cats = await categoryRepo.findMany(
    { id: { in: categoryIds } },
    { id: true, name: true, icon: true, color: true }
  );

  return cats
    .map((cat) => {
      const data = categoryMap.get(cat.id) ?? { expenseTotal: 0, incomeTotal: 0, count: 0 };
      return {
        category: cat,
        expenseTotal: data.expenseTotal,
        incomeTotal: data.incomeTotal,
        count: data.count,
        netTotal: data.incomeTotal - data.expenseTotal,
      };
    })
    .sort((a, b) => b.expenseTotal - a.expenseTotal);
}

export async function getReceiptItems(transactionId: string, userId: string) {
  // Verify transaction belongs to user
  await getTransactionById(transactionId, userId);

  return transactionRepo.findReceiptItems(transactionId);
}

async function assertOwnership(
  userId: string,
  refs: { accountId?: string; categoryId?: string; fixedExpenseId?: string },
  tx: Prisma.TransactionClient = prisma
): Promise<void> {
  if (refs.accountId) {
    const ok = await tx.account.findFirst({
      where: { id: refs.accountId, userId },
      select: { id: true },
    });
    if (!ok) throw new NotFoundError('Cuenta no encontrada');
  }
  if (refs.categoryId) {
    const ok = await tx.category.findFirst({
      where: { id: refs.categoryId, userId },
      select: { id: true },
    });
    if (!ok) throw new NotFoundError('Categoría no encontrada');
  }
  if (refs.fixedExpenseId) {
    const ok = await tx.fixedExpense.findFirst({
      where: { id: refs.fixedExpenseId, userId },
      select: { id: true },
    });
    if (!ok) throw new NotFoundError('Gasto fijo no encontrado');
  }
}
