-- AlterTable: Add autoGenerate to FixedExpense
ALTER TABLE "FixedExpense" ADD COLUMN "autoGenerate" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable: Add isAutoGenerated to Transaction
ALTER TABLE "Transaction" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
