export const ICON_EMOJI: Record<string, string> = {
  Utensils: '🍴',
  Car: '🚗',
  Home: '🏠',
  Lightbulb: '💡',
  Gamepad2: '🎮',
  Shirt: '👕',
  Stethoscope: '🩺',
  GraduationCap: '🎓',
  ShoppingCart: '🛒',
  Smartphone: '📱',
  Wallet: '👛',
  Briefcase: '💼',
  TrendingUp: '📈',
  Gift: '🎁',
  Banknote: '💵',
  Coffee: '☕',
  Plane: '✈️',
  Train: '🚂',
  Bus: '🚌',
  Bike: '🚲',
  Music: '🎵',
  Film: '🎬',
  Book: '📚',
  Heart: '❤️',
  Star: '⭐',
  Globe: '🌍',
  Zap: '⚡',
  Shield: '🛡️',
  Tool: '🔧',
  Wrench: '🔧',
  Package: '📦',
  Tag: '🏷️',
  CreditCard: '💳',
  DollarSign: '💲',
  PiggyBank: '🐷',
  Building: '🏢',
  Baby: '👶',
  Paw: '🐾',
  Dumbbell: '🏋️',
  Scissors: '✂️',
  Fuel: '⛽',
};

export function resolveIcon(icon?: string): string {
  if (!icon) return '';
  return ICON_EMOJI[icon] ?? '';
}
